# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db3.cwsberv5qdba.us-east-1.rds.amazonaws.com:3306/realmeet?serverTimezone=UTC&useSSL=false
    username: root